In [1]:
import os 
os.chdir(os.path.dirname(os.getcwd()))

In [2]:

from credential_accessor import CredentialAccessor 
from dao.google_bigquery import GoogleBigQuery as gbq 

creds_accessor = CredentialAccessor(env = "prod", on_server= False)
myGBQ = gbq(attr = creds_accessor.get_attr())


from datetime import datetime, date, timedelta
from dateutil.relativedelta import relativedelta

import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import itertools
import random
from random_batch import *

In [6]:
random_batch,bincount_=create_random_set(10)
print(f'Batches for this group :\n{random_batch}\nBincount :\n{np.arange(10)}\n{bincount_}')

Product array for this arrangement was already done at : /srv/ds_project/Indra_proj/dsp_gamification_experiment/outputs/random_prd_arr_id/n10_appear3_setsize3.pickle
Batches for this group :
[[6 2 8]
 [3 5 8]
 [0 4 1]
 [0 7 6]
 [3 2 0]
 [3 1 9]
 [6 5 4]
 [7 2 5]
 [7 9 8]
 [9 4 1]]
Bincount :
[0 1 2 3 4 5 6 7 8 9]
[3 3 3 3 3 3 3 3 3 3]


In [56]:
def random_diagonal(n_row = 15, *args, **kwargs):
    arr = np.ones([n_row,n_row])*-1
    list_id = list(np.arange(n_row))
    for i in range(n_row):
        arr[:,i] = list_id 
        list_id = shift_right_list(list_id)
    return arr.astype(int)
s = random_diagonal(14)

In [57]:
print(s)

[[ 0 13 12 11 10  9  8  7  6  5  4  3  2  1]
 [ 1  0 13 12 11 10  9  8  7  6  5  4  3  2]
 [ 2  1  0 13 12 11 10  9  8  7  6  5  4  3]
 [ 3  2  1  0 13 12 11 10  9  8  7  6  5  4]
 [ 4  3  2  1  0 13 12 11 10  9  8  7  6  5]
 [ 5  4  3  2  1  0 13 12 11 10  9  8  7  6]
 [ 6  5  4  3  2  1  0 13 12 11 10  9  8  7]
 [ 7  6  5  4  3  2  1  0 13 12 11 10  9  8]
 [ 8  7  6  5  4  3  2  1  0 13 12 11 10  9]
 [ 9  8  7  6  5  4  3  2  1  0 13 12 11 10]
 [10  9  8  7  6  5  4  3  2  1  0 13 12 11]
 [11 10  9  8  7  6  5  4  3  2  1  0 13 12]
 [12 11 10  9  8  7  6  5  4  3  2  1  0 13]
 [13 12 11 10  9  8  7  6  5  4  3  2  1  0]]


In [44]:
np.array(shift_right_list(list(np.arange(20))))+1

array([20,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [145]:
def split_array(arr : np.array, set_max : bool = None, n_groups : int = None):
    if n_groups is not None :
        if n_groups > arr.shape[0] :
            raise ValueError("The number of groups is more than number of items")
        else :
            return np.array_split(arr,n_groups)
    if set_max is not None :
        if set_max > arr.shape[0] :
            raise ValueError("The number of groups is more than number of items")
        else : 
            n_groups = int(np.ceil(arr.shape[0]/set_max))
            split_index = [int(set_max*i) for i in range(1,n_groups+1)]
            split_index[-1] = arr.shape[0]
            splitted_arr = np.split(arr,split_index)
            delete_last_items_ = splitted_arr.pop()
            return splitted_arr
        
            

In [161]:
split_array([f'BOCIMI_{str(x).zfill(2)}' for x in range,n_groups=3)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10])]

In [138]:
np.array_split(np.arange(11),7)

[array([0, 1]),
 array([2, 3]),
 array([4, 5]),
 array([6, 7]),
 array([8]),
 array([9]),
 array([10])]

In [9]:
np.arange(0,3,1)

array([0, 1, 2])

In [41]:
np.arange(2,7,2)

array([2, 4, 6])

In [91]:
for i in range(1,5):
    print(i)

1
2
3
4


In [153]:
'1245'.zfill(2)

'1245'

In [160]:
np.where(np.bincount([1,3,4,3,5])==2)

(array([3]),)

In [168]:
for x in [np.array([1]),np.array([2,3,4])]:
    for j in x:
        print(j)

1
2
3
4
